language: generic

sudo: false

matrix:
  include:
    - os: linux
      env: CXX=g++-4.8
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-4.8' ]
      # override before_install to use apt installed compiler
      # rather than mason installed clang++
      before_install:
        - which ${CXX}
    - os: linux
      env: CXX=g++-4.9 CXXFLAGS="-Weffc++"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-4.9' ]
      # override before_install to use apt installed compiler
      # rather than mason installed clang++
      before_install:
        - which ${CXX}
    - os: linux
      env: CXX=g++-5 CXXFLAGS="-Weffc++"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5' ]
      # override before_install to use apt installed compiler
      # rather than mason installed clang++
      before_install:
        - which ${CXX}
    - os: linux
      env: CXX=g++-6
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-6' ]
      # override before_install to use apt installed compiler
      # rather than mason installed clang++
      before_install:
        - which ${CXX}
    - os: linux
      env: CXX=clang++ CXXFLAGS="-flto"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      env: CXX=clang++ LLVM_VERSION="4.0.0" CXXFLAGS="-flto"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      env: CXX=clang++ CXXFLAGS="-flto -fsanitize=cfi -fvisibility=hidden"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      env: CXX=clang++ CXXFLAGS="-fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -fno-common"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      env: CXX=clang++ CXXFLAGS="-fsanitize=undefined"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      env: CXX=clang++ CXXFLAGS="-fsanitize=integer"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    # OS X / apple clang / xcode 7.x
    - os: osx
      osx_image: xcode7.3
      env: CXX=clang++
      # override before_install to use apple clang
      before_install:
        - which ${CXX}
    # coverage build
    - os: linux
      sudo: false
      env: CXXFLAGS="--coverage" LDFLAGS="--coverage"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
      script:
        - make debug
        - make test
        # MASON_LLVM_RELEASE comes from the setup.sh script
        - mason install llvm-cov ${MASON_LLVM_RELEASE}
        - mason link llvm-cov ${MASON_LLVM_RELEASE}
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ./codecov -x "llvm-cov gcov" -Z

before_install:
 - git submodule update --init
 - export LLVM_VERSION="${LLVM_VERSION:-3.9.1}"
 - |
   if [[ ${CXX} == "clang++" ]]; then
    ./mason.sh install clang++ ${LLVM_VERSION}
    export PATH=$(./mason.sh prefix clang++ ${LLVM_VERSION})/bin:${PATH}
    ./mason.sh install binutils 2.27
    export PATH=$(./mason.sh prefix binutils 2.27)/bin:${PATH}
   fi
 - which ${CXX}

before_script:
 - make release
 - make test
 - make clean
 - make debug
 - make test

