language: generic
sudo: false

matrix:
  include:
    - os: linux
      env: CXX=g++-5
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5' ]
    - os: linux
      env: CXX=clang++-3.7 MASON_CLANG=true
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
    - os: osx
      osx_image: xcode7.3

cache: apt

before_install:
 - ./travis_setup.sh

script:
 - make test
